USE [master]
GO

/****** Object:  Database [dotnetpractise]    Script Date: 12/23/2012 1:57:55 AM ******/
CREATE DATABASE [dotnetpractise]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dotnetpractise', FILENAME = N'dotnetpractise.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'dotnetpractise_log', FILENAME = N'dotnetpractise_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [dotnetpractise] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dotnetpractise].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dotnetpractise] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dotnetpractise] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dotnetpractise] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dotnetpractise] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dotnetpractise] SET ARITHABORT OFF 
GO

ALTER DATABASE [dotnetpractise] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dotnetpractise] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [dotnetpractise] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dotnetpractise] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dotnetpractise] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dotnetpractise] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dotnetpractise] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dotnetpractise] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dotnetpractise] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dotnetpractise] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dotnetpractise] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dotnetpractise] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dotnetpractise] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dotnetpractise] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dotnetpractise] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dotnetpractise] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dotnetpractise] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dotnetpractise] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dotnetpractise] SET RECOVERY FULL 
GO

ALTER DATABASE [dotnetpractise] SET  MULTI_USER 
GO

ALTER DATABASE [dotnetpractise] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dotnetpractise] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dotnetpractise] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dotnetpractise] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [dotnetpractise] SET  READ_WRITE 
GO


