//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKASP.DOMAIN.EntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public int Creator { get; set; }
        public int Topic { get; set; }
        public string Text { get; set; }
        public System.DateTime Created_on { get; set; }
    
        public virtual Topic Topic1 { get; set; }
        public virtual Usr_lg_data Usr_lg_data { get; set; }
    }
}
