//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKASP.DOMAIN.EntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usr_lg_data
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string SubName { get; set; }
        public string loginstr { get; set; }
        public string passwd { get; set; }
        public System.DateTime created_on { get; set; }
    }
}
